name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'    

      - id: 'npm-auth'
        name: 'Authenticate to GCP Artifact Registry'
        run: npx google-artifactregistry-auth ./src/ClientApp/.npmrc          

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Generate SQL
        run: |
          cd ./src
          dotnet tool install --project ./src --global dotnet-ef
          dotnet ef migrations script -o ./bin/database.sql

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            bin
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'

      - id: 'npm-auth'
        name: 'Authenticate to GCP Artifact Registry'
        run: npx google-artifactregistry-auth ./src/ClientApp/.npmrc                    

      - id: 'sdk'
        name: 'Setup Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'configure-docker'
        name: 'Configure docker'
        run: |
          gcloud auth configure-docker australia-southeast2-docker.pkg.dev

      - id: 'docker'
        name: 'Build and push image'
        uses: 'docker/build-push-action@v2'
        with:
          context: .
          push: true
          tags: australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/bmwadforth-blogwebsite:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build, publish ]
    if: github.ref == 'refs/heads/master'

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'

      - id: 'npm-auth'
        name: 'Authenticate to GCP Artifact Registry'
        run: npx google-artifactregistry-auth ./src/ClientApp/.npmrc                    

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          region: 'australia-southeast1'
          service: 'bmwadforth-blogwebsite'
          image: 'australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/bmwadforth-blogwebsite:latest'